language: c
compiler: gcc
os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - realpath
    - gcc-4.8
    - g++-4.8

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: ./build.sh

after_failure: cat logfile_* | nc termbin.com 9999

after_success: curl -i -X POST -F "file=@$(ls *.tgz)" -F "expire=86400" -F "submit=Upload%20it!" http://tempsend.com/send

branches:
  only:
  - master
